name: fleetmanagement
description: DGF TRACKING.

version: 2.0.10+10

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^6.9.1
  responsive_framework: ^0.2.0
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  rflutter_alert: ^2.0.4
  geolocator: ^9.0.2
  flutter_phoenix: ^1.1.0

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^2.0.15

  # A composable, Future-based library for making HTTP requests.
  http: ^0.13.5

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^6.0.3

  # String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^3.0.0

  # A powerful Http client for Dart
  dio: ^4.0.6

  # A flexible widget for user notification. Customize your text, button, duration, animations
  # and much more. For Android devs, it is made to replace Snackbars and Toasts.
  another_flushbar: ^1.10.24

  # Material Dialog
  material_dialog: ^1.0.0-nullsafety.1

  # This package provides internationalization and localization facilities, including message
  # translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0

  # XXTEA is a fast and secure encryption algorithm. This is a XXTEA library for Dart.
  xxtea: ^2.1.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  sembast: ^3.1.1


  # for dependency injection
  get_it: ^7.2.0

  #for state management
  bloc: ^7.2.1
  flutter_bloc: ^7.3.0


  #for validate email in form
  email_validator: ^2.0.1

  #for color hex code
  hexcolor: ^2.0.5

  #defines annotations
  meta: ^1.7.0

  #hat helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.0

  #for discovering the state of the soft-keyboard visibility on Android and iOS.
  flutter_keyboard_visibility: ^5.0.3

  #google map
  google_maps_flutter: ^2.1.10
  location: ^4.2.0
  flutter_google_street_view: ^3.1.2
  map_launcher: ^2.3.0+1

  #for select car on map car list
  scroll_snap_list: ^0.9.1

  #for custom calendar
  table_calendar: ^3.0.2

  #line icons
  line_icons: ^2.0.1
  line_awesome_flutter: ^2.0.0

  #for chart
  fl_chart: ^0.40.0
  charts_flutter: ^0.11.0

  #for pretty logging
  pretty_dio_logger: ^1.1.1

  #for map cluster
  fluster: ^1.2.0

  #uuid
  uuid: ^3.0.6

  #log
  logger: ^1.1.0

  #for slide vehicle
  carousel_slider: ^4.1.1

  #for customize map marker
  marker_icon: ^0.7.1

  #for cache image
  cached_network_image: ^3.2.1

  #for bottom sheet
  modal_bottom_sheet: ^2.1.0

  #for localization
  flutter_translate: ^4.0.3

  #smart refresher
  pull_to_refresh: ^2.0.0

  #for contact
  url_launcher: ^6.1.5

  #for live video and video playback
  video_player: ^2.4.10
  flutter_inappwebview: ^5.7.2+3

  #for video loading
  liquid_progress_indicator: ^0.4.0
  pointer_interceptor: ^0.9.3+2

  # for driver sign
  signature: ^5.0.0
  image_picker: ^0.8.4+10
  http_parser: ^4.0.0
  flutter_native_image: ^0.0.6+1
  flutter_spinkit: ^5.1.0
  file_picker: ^4.5.1
  open_file: ^3.2.1
  high_chart: ^2.0.1
  flutter_downloader: ^1.8.1
  permission_handler: ^10.0.0
  path_provider: ^2.0.9
  android_path_provider: ^0.3.0
  device_info_plus: ^4.0.0
  flutter_local_notifications: ^9.7.0
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  webview_flutter: ^3.0.4
  internet_connection_checker: ^0.0.1+4
  floating_action_bubble: 1.1.4
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter


  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/i18n/en.json
    - assets/i18n/th.json
    - assets/original_bg.png
    - assets/login_bg.png
    - assets/splash_bg.png
    - assets/line.png
    - assets/login_logo.png
    - assets/car.png
    - assets/svg/point_car.svg
    - assets/svg/routeA.svg
    - assets/svg/routeB.svg

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/KanitMedium.ttf
        - asset: assets/fonts/KanitRegular.ttf
    - family: CustomFontIcons
      fonts:
        - asset: assets/fonts/ParkingFont.ttf

