// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBH8mT7D-6YXHSufRS_3lM7hXhp_JflUzk',
//     appId: '1:64958677122:web:509ada3378c2a21b16749b',
//     messagingSenderId: '64958677122',
//     projectId: 'dgf-fcm',
//     authDomain: 'dgf-fcm.firebaseapp.com',
//     storageBucket: 'dgf-fcm.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDl5VYgLuvuNc1X_vP6XFCeZr1H7QNvOn0',
//     appId: '1:64958677122:android:a201477d658bca9016749b',
//     messagingSenderId: '64958677122',
//     projectId: 'dgf-fcm',
//     storageBucket: 'dgf-fcm.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDJI4tYHeuv3xHMmsOpsgWXTdUpqBD0Jwk',
//     appId: '1:64958677122:ios:401dbc5fa45a91c716749b',
//     messagingSenderId: '64958677122',
//     projectId: 'dgf-fcm',
//     storageBucket: 'dgf-fcm.appspot.com',
//     iosClientId: '64958677122-1cn3gmndigo0fgqjm7hfekbqshcqbt53.apps.googleusercontent.com',
//     iosBundleId: 'com.dgffleetmgm.th.fleetmanagement.app',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDJI4tYHeuv3xHMmsOpsgWXTdUpqBD0Jwk',
//     appId: '1:64958677122:ios:1305a5bae7cc156816749b',
//     messagingSenderId: '64958677122',
//     projectId: 'dgf-fcm',
//     storageBucket: 'dgf-fcm.appspot.com',
//     iosClientId: '64958677122-gce096pa8q593oktd7jil2727md8oqp5.apps.googleusercontent.com',
//     iosBundleId: 'com.dgffleetmgm.th.fleetmanagement',
//   );
// }
